### ISSUE TITLE
Warning in generate1

### ISSUE THREAD

**Issue by hbrunie** [hbrunie/conus#1]
conus_random.cpp: In member function 'virtual double ConusUniformCPU::generate1()':
conus_random.cpp:27:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Throw an exception if buf_ptr >=  buf_len ?

**Comment by JBlaschke** [comment]
Yea... I fixed that with recursion... now if it get there, it will generate a new bunch, and then recurse into `generate1()`. Since it has been replenished (in theory), it will return safely.

Note that we might want to put some check in though ... just to be sure :P
